### ISSUE TITLE
Ошибка при обработке ленты

### ISSUE THREAD

**Issue by bcskda** [Reedych/vkfeed2rss#3]
Что делал:
```$ vkfeed2rss {-d domain | -s uid}```
Что получилось:
```...
...
<generator>vkfeed2rss v0.2</generator>
vkfeed2rss: произошла ошибка при обработке ленты: : <string>
```
[Скрин на imgur.com](https://imgur.com/a/mgJqT)
Версия: 0.2-beta (c698f43)
[UPD]:
- clang-3.9.1
- jansson-2.9
- curl-7.54.1

**Comment by Reedych** [comment]
Я об этом писал бугурт: https://pastebin.com/94A9DGNq

Если коротко, то вк обновили АПИ, а что обновили понял не сильно. Они какие-то ключи для приложения требуют, а у меня аккаунта нет. На месяце починю.

**Comment by bcskda** [comment]
Окей, glgl

**Comment by Reedych** [comment]
Приложение починено. Оказалось, что нужно дать приложению сервисный ключ. Правда хз можно ли его публиковать, но норм. Добавил одну строчку и впринципе всё.
